# Generated by Django 5.2.10 on 2026-01-31 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crashblog', '0005_remove_post_posts_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('draft', 'Draft')], default='active', max_length=10),
        ),
    ]
